[package]
name = "s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.10.1"
clap = { version = "3.2.20", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.5"
